version: '3.4'

services:
  redis_container:
    container_name: redis
    image: redis:3
    ports:
      - "6379:6379"

  mongo_container:
    container_name: mongo
    image: mongo
    #restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./Mongodb/mongodbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpwd
